### ISSUE TITLE
Build failure due to missing map `bgnpcgn-ron-cyrl-latn-2002_main.json`

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript.org#80]
```
Trace: Error: ENOENT: no such file or directory, open './map/vis_json/bgnpcgn-ron-cyrl-latn-2002_main.json'
179
    at Object.openSync (fs.js:497:3)
180
    at Object.readFileSync (fs.js:393:35)
181
    at _callee4$ (/home/runner/work/interscript.org/interscript.org/static.config.js:288:52)
182
    at tryCatch (/home/runner/work/interscript.org/interscript.org/node_modules/regenerator-runtime/runtime.js:63:40)
183
    at Generator.invoke [as _invoke] (/home/runner/work/interscript.org/interscript.org/node_modules/regenerator-runtime/runtime.js:294:22)
184
    at Generator.next (/home/runner/work/interscript.org/interscript.org/node_modules/regenerator-runtime/runtime.js:119:21)
185
```

**Comment by ronaldtse** [comment]
Looks like the map has been renamed (`cyrl-latn` to `Cyrl-Latn`), but the vis_json.zip file is still giving the old name:
https://github.com/interscript/interscript/releases/latest/download/vis_json.zip

Will need to update the release.

**Comment by webdev778** [comment]
Already fixed and confirmed
